[package]
name = "duse"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
size = "0.4.1"
num_cpus = "1.16.0"
crossbeam = "0.5"
clap = { version = "4.5.11", features = ["derive"] }
